---

- name: iptables_save
  shell: iptables-save > /etc/sysconfig/iptables

- name: iptables_restart
  systemd:
    name: iptables
    state: reloaded

- name: zabbix_agent_restart
  command: systemctl restart zabbix-agent

- name: httpd_restart
  systemd:
    name: httpd
    state: reloaded
